# Install kubectl utility by instructions from https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux
RUN curl -Lo /usr/local/bin/kubectl https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl \
  && chmod +x /usr/local/bin/kubectl \
  && ln -s /usr/local/bin/kubectl /usr/local/bin/k

# Install krew plugin by instruction from https://krew.sigs.k8s.io/docs/user-guide/setup/install/#bash
RUN ( \
  set -x; cd "$(mktemp -d)" \
  && OS="$(uname | tr '[:upper:]' '[:lower:]')" \
  && ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" \
  && KREW="krew-${OS}_${ARCH}" \
  && curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" \
  && tar zxvf "${KREW}.tar.gz" \
  && mv ./"${KREW}" /usr/local/bin/kubectl-krew \
  && mkdir /usr/lib/krew \
  )
ENV KREW_ROOT="/usr/lib/krew"

# Install kubectx + kubens from https://github.com/ahmetb/kubectx
RUN kubectl krew install ctx && kubectl krew install ns
